media: src/assets
content:
  - name: projects
    label: projects
    type: collection
    path: src/pages/projects
    fields:
      - name: title
        type: string
      - name: client
        type: string
      - name: body
        type: rich-text